# Configuration de la connexion MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_deces?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration Hibernate / JPA
# "update" permet de créer les tables automatiquement à partir de vos classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect