package ma.chu.gestiondeces.dossier;

public enum StatutDossier {
    CREE_PAR_BAF,
    CODE_CADAVRE_ASSOCIE,
    EN_ATTENTE_VERIFICATION,
    CERTIFICAT_CONFORME_VALIDE,
    PRET_POUR_TRANSFERT,
    PRIS_EN_CHARGE_PAR_AMBULANCIER,
    EN_COURS_DE_TRANSFERT,
    ARRIVE_A_LA_MORGUE,
    CLOTURE,
    ANOMALIE_DETECTEE,
    EN_ATTENTE_CORRECTION,
    ANNULE
}